<template>
    <section class="privacy">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h2 class="text-center">Privacy &amp; Policy</h2>
                    <hr/>
                </div>
                <div class="col-lg-12">
                    <h3>VTC, LLC Privacy Policy</h3>
                    <h4>Effective August 12, 2022</h4>
                    <p class="mt-4">The following Privacy Policy (the “Policy”) outlines the policies and procedures VTC, LLC (“Videotc”) uses in association with the collection, use, and disclosure of your information on the Videotc.com and videotimecapsule.com websites (“Website”) and the services, features, content, or applications Videotc offers (collectively, with the Website, referred to as “Services”). Your information may be obtained from multiple sources including information you submit through the Website or to Videotc and/or information obtained from various third parties and/or services.</p>
                    <p>Videotc owns and operates the Website and is committed to your privacy. Videotc demonstrates this commitment by posting this privacy policy (“Privacy Policy”) to inform you of:</p>
                    <ol>
                        <li>The Personal Data Videotc collects from you through the Website and Services;</li>
                        <li>How Videotc uses the information;</li>
                        <li>With whom Videotc shares the information and why;</li>
                        <li>Your choices regarding collection, use, and distribution of the information;</li>
                        <li>The security procedures in place to protect the information under Videotc’ control;</li>
                        <li>How you can correct any inaccuracies in the information;</li>
                        <li>Procedures relating to unauthorized usage of the Website; and</li>
                        <li>Changes to this Privacy Policy.</li>
                    </ol>
                    <p>NO ONE UNDER THE AGE OF 13 MAY USE THIS WEBSITE. YOUR USE OF THIS WEBSITE CONSTITUTES YOUR AGREEMENT TO THE COLLECTION AND USE OF YOUR PERSONAL INFORMATION PURSUANT TO THE TERMS AND CONDITIONS SET FORTH UNDER THIS AGREEMENT.  IF YOU DO NOT AGREE TO THE TERMS OF THIS PRIVACY POLICY, YOU ARE NOT AUTHORIZED TO USE THE WEBSITE.</p>
                    <h3>INFORMATION COLLECTION</h3>
                    <h3>GDPR</h3>
                    <p>If you are a resident of the European Union, United Kingdom, Norway, Iceland, or Lichtenstein, you may have additional rights under European Union Regulation (EU) No. 2016/679 of 27 April 2016, also known as the General Data Protection Regulation or GDPR (the “GDPR”) that covers the collection and use of your Personal Data, as outlined above. For purposes of the GDPR, Videotc may be the controller and/or processor of your Personal Data processed in connection with the Services. If you have any questions about this Privacy Policy or whether any of the following applies to you, please contact us at info@Videotc.com In the event Videotc is the processor, but not the controller of your Personal Data, please contact the controller of your Personal Data (i.e., the individual or entity that provided the goods or services in connection with which you provided your Personal Data) to enforce your rights regarding such Personal Data.</p>
                    <p>Under the GDPR your rights are as follows:</p>
                    <ul>
                        <li>the right to be informed about how your Personal Data will be used;</li>
                        <li>the right of access to your Personal Data;</li>
                        <li>the right to rectification if any of your Personal Data is recorded incorrectly;</li>
                        <li>the right to erasure of your Personal Data;</li>
                        <li>the right to restrict processing of your Personal Data;</li>
                        <li>the right to portability of your Personal Data in a machine-readable format;</li>
                        <li>the right to object to further use or disclosure of your Personal Data; and</li>
                        <li>the right not to be subject to automated decision-making including profiling</li>
                        <li>the right to file a complaint with the supervisory authority of your country or EU Member State concerning Videotc’ handling of your Personal Data</li>
                    </ul>
                    <p>Videotc collects certain Information about you when you visit, or register with, the Website or purchase products or services through the Website. This information may either be Personal Data or non-Personal Data.</p>
                    <h3>Personal Data</h3>
                    <p>Personal Data is information that identifies a specific user of the Website. When you register on the Website, we record Information you submit in association therewith, including your name, email address and password. We may ask you to provide certain information about yourself when you: 1) order a product or service through the Website and/or from one of our partners; 2) submit feedback; 3) enter our contests or sweepstakes; 4) respond to a survey; 5) submit content in our discussion forums; 6) post a review; 7) request information or 8) sign up for special offers through the Website (collectively, “ID Actions”). The information we request you to provide may include, but is not limited to, your: 1) first and last name; 2) email address; 3) telephone number; 4) gender; 5) musical preferences; 6) mailing address; 7) hometown; 8) geographic location; and 9) date of birth. In addition, when you use the Website, Videotc may automatically collect the following information: 1) IP address; 2) Web browser information; 3) access device information; 4) page view history and information; 5) usage and click tracking; 6) transaction information (including date, time, amount, etc.), cookies; and 7) usage data (including access time and length, and hardware and software data).</p>
                    <p>When you request products or services through the Website, we may also ask you to provide us with your credit card number, expiration date and authentication codes or related information. While engaging in ID Actions is optional, if you do not provide the information requested in association with a particular activity, you may not be permitted to engage in that activity. If you provide us with a referral, that includes Personal Data relating to a third party, we will send the third party an invitation to register with the Website. We store this third-party information solely for the purpose of sending the third-party the invitation and gauging the success of the referral program. If the third party elects to register with the Website, all Personal Data collected from the third party will be collected in accordance with this Privacy Policy. At any time, the third party may request this information be removed from our database by sending the request to <a href="mailto:info@Videotc.com">info@videotc.com</a>.</p>
                    <h3>Non-Personal Data</h3>
                    <p>Non-Personal Data is information that does not identify a specific user of the Website. When you visit the Website, Videotc may record your cookie information and the webpages within the Website that you visit, your downloads, the time you spend on the Website, the Uniform Resource Locator (“URL”) of the website you visited before coming to the Website, the URL of the website you visit after leaving the Website, your Internet protocol (IP) address and the type of browser you are using. Advertisers on the website and third-party service providers may use cookies, web beacons, pixel tags or similar tools to automatically collect this information when you visit the Website.</p>
                    <p>A cookie is a piece of data stored on your hard drive by a website containing information about you in relation to that website. Usage of a cookie is in no way linked to any Personal Data while on the Website.  When you log on to the Website, an encrypted authentication cookie is created on your computer to manage your Website session.  Once you log off or close your web browser, the authentication cookie is deleted.  The Website may also create other cookies to facilitate your use of the Website.  If you reject cookies, you may still use the Website.  The only drawback to this is that you will be limited in some areas of the Website.  Cookies can also enable us to track and target your interests to enhance your experience on the Website.</p>
                    <p>Some of our business partners may use cookies on the Website (for example, advertisers). However, we have no access to or control over these cookies.  The Website may also contain links to other Websites. Please be aware that Videotc is not responsible for the privacy practices of such other websites. We encourage you to note when you leave the Website and read the privacy statements of each website that collects Personal Data.  This Privacy Policy only applies to information collected by the Website.</p>
                    <h3>Payment Processing</h3>
                    <p>To collect your payments Videotc uses PayPal and Stripe as third-party payment processors. Videotc may collect payment information from you to be used solely to collect and provide payments related to the Services, and is only stored by  PayPal and/or Stripe. You should review the terms of service and privacy policies of  PayPal and Stripe, available <a href="https://www.paypal.com/us/webapps/mpp/ua/useragreement-full?locale.x=en_US" target="_blank">PayPal User Agreement</a>, <a href="https://www.paypal.com/myaccount/privacy/privacyhub" target="_blank">PayPal Privacy</a>, <a href="https://stripe.com/ssa" target="_blank">Stripe Services Agreement</a> and <a href="https://stripe.com/privacy" target="_blank">Stripe Privacy</a></p>
                    <h3>USE OF INFORMATION</h3>
                    <p>Videotc only “processes” your Personal Data as a “processor” if it has a lawful reason to do so. Lawful reasons for processing your Personal Data include contractual necessity, your consent, and the following “legitimate interests” of Videotc or others: 1) Contract - Videotc processes the following Personal Data as a matter of “contractual necessity,” namely processing the data to perform obligations and enforce rights under the Website Terms of Service: a) First and last name; b) Email address; c) Content provided by you (may include Personal Data if you provide it); d) IP address; and/or e) Billing zip code and/or country of residence; 2) Consent - Videotc processes Personal Data based on consent you expressly provide; 3) Legitimate Interest -  Videotc processes the following Personal Data to further the legitimate interests of Videotc or third-parties: a) First and last name; b) Email address; c) IP address; and/or d) Billing zip code and/or country of residence; an 4) Other - Videotc may process your Personal Data to comply with legal obligation or to protect your interests, the interests of others, and/or the public interest.</p>
                    <p>Videotc uses your Personal Data to provide you with products, services and information, improve our products and services, improve the Website, analyze trends, enhance the Website, improve our marketing and promotion, administer the Website, and customize your experience both on the Website and with third parties as provided under the “Sharing Information” section outlined below. Prior to Videotc using any of your Personal Data in a public manner, such as for marketing or on a publicly accessible portion of the Website, we will obtain your consent. You hereby acknowledge that Videotc has no control over any Personal Data you personally post to a public portion of the Website or release publicly. If you unsure as to which portions of the Website are publicly accessible, please contact <a href="mailto:info@videotc.com">info@videotc.com</a> with any questions prior to posting any Personal Data. We may also store your Personal Data if you use the Website to send information or a product to another person. Other ways we use your Personal Data include: troubleshooting, Website administration, addressing support issues, personalizing your Website experience, preventing illegal or harmful activities, identifying useful general statistical information, resolving disputes, communicating with customers, enforcing the Website Terms of Use, Privacy Policy and other agreements with you, complying with applicable law, responding to subpoenas, and cooperating with law enforcement. For security reasons, your Internet protocol address may be linked to other Personal Data about you.</p>
                    <p>Videotc uses your Non-Personal Data for troubleshooting, Website administration and trend analysis, as well as for demographic information collection and analysis. We may also share this Non-Personal Data with authorized Third-Party Service Providers and Advertisers to track the effectiveness of various products, advertising, services, content, and programming. We also use the information you provide us to gather broad demographic information for non-personally identifiable aggregate use.</p>
                    <p>Any information you publicly post or upload to the Website will be publicly available in accordance with the most current version of the Website’s Terms of Use and are not considered protected information under this Privacy Policy.</p>
                    <h3>SHARING INFORMATION</h3>
                    <p>Videotc may share aggregate, non-personally identifiable demographic information with its partners and advertisers.  Videotc will not share your personal information with any nonaffiliated companies except in furtherance of providing you goods or services that you have specifically requested.  When we share your personal information with nonaffiliated companies, we do so only under the terms of a confidentiality agreement which prohibits the nonaffiliated companies from sharing your personal information with others.  We may also share your personal information in response to subpoenas, court orders, or in exercise or defense of our legal rights.  In the event Videotc merges with another company, your personal information shall be transferred to such other company.</p>
                    <h3>CHOICES REGARDING INFORMATION COLLECTION</h3>
                    <p>You have the option to ‘opt-out’ of having your information used for purposes not related to the Website at the point where we ask for the information.</p>
                    <p>If you no longer wish to receive information from us, such as email alerts, you may opt-out of receiving these communications by replying to unsubscribe in the subject line in the e-mail, or e-mail us at <a href="mailto:info@videotc.com">info@videotc.com</a>.</p>
                    <h3>Social Media</h3>
                    <p>The Website allows you to access social media sites such as Facebook to interact with others and to share information. If you connect to a social media site through the Website, such as "Connect with Facebook" your profiles will merge. By merging your accounts you are allowing the Website to access your information and you are agreeing to the terms of use of the associated social media website. You have the option to disable such social media connections at any time by logging into "Profile" on the Website.  You may also disable the connection through the social media website.</p>
                    <h3>ORDERS</h3>
                    <p>We request information from you when you make a purchase through the Website. You may be asked to provide contact information (like name and shipping address) and financial information (like credit card number, expiration date). This information is used for billing purposes and to fill your orders. If we have trouble processing an order, this contact information is used to get in touch with you.</p>
                    <h3>SECURITY</h3>
                    <p>This Website utilizes several security measures to prevent the loss, corruption or unauthorized dissemination of the information collected on this Website. Regardless of the security measures undertaken, however, no website operator can guarantee the security or privacy of data collected. Accordingly, despite our efforts to constantly monitor and upgrade our security measures, there will always remain a slight possibility that the data may become compromised. If at any time you become aware of any problems with Videotc’ security procedures, please contact the webmaster immediately at <a href="mailto:info@videotc.com">info@videotc.com</a> so that we may review and correct any problems.</p>
                    <h3>CORRECTING INFORMATION</h3>
                    <p>If your Personal Data is incorrect or changes, or if you no longer desire our products or services, we will endeavor to provide a way to correct, update or remove your personal data from our files. This can be in writing to Videotc at:</p>
                    <p>VTC, LLC<br>320 North 3rd Street<br>Suite 100<br>Burlington, Iowa 52601</p>
                    <p>You can also do this by e-mailing our webmaster at <a href="mailto:info@videotc.com">info@videotc.com</a>.</p>
                    <h3>UNAUTHORIZED USAGE</h3>
                    <p>If at any time Videotc becomes aware of any unauthorized usage of this Website, including any unauthorized political, commercial, malicious, destructive or illegal use, Videotc may, at its discretion, purge the information and/or report any such activities to the relevant authorities.  If you become aware of any such unauthorized usage of the Website, please contact the webmaster immediately at <a href="mailto:info@videotc.com">info@videotc.com</a>.</p>
                    <h3>POLICY CHANGES</h3>
                    <p>You acknowledge that Videotc may modify this Privacy Policy at any time, without notice to you. Your use of the Website subsequent to such changes shall constitute Your acceptance of, and agreement to, such revised terms.</p>
                </div>
            </div>
        </div>
    </section>
</template>