<template>
    <section class="terms">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h2 class="text-center">Terms of Use</h2>
                    <hr/>
                </div>
                <div class="col-lg-12">
                    <h3>VTC, LLC (“Videotc”) Terms of Use</h3>
                    <h4>Effective July 26, 2021</h4>
                    <p class="mt-4">The following Terms of Use (the “Agreement”) outlines what Videotc expects of you and what you can expect from Videotc when you access Videotc.com  and Videotimecapsule.com websites (“Website”), as well as the associated applications (“Applications”) and services (the Website, Applications, and other Videotc services being collectively referred to as the “Services”). It is important that you read and understand these Terms of Use so that you are aware of your rights and obligation when accessing the Services.</p>                    
                    <p>By accessing this website, you acknowledge that you are either: 1) at least 18 years of age; or 2) at least 13 years of age AND accessing the Services with the permission of your parent and/or legal guardian.  By accessing this website, you also acknowledge that all of the information you provide through the Services shall be correct and complete. Additional terms governing your use of the Services may apply and will be disclosed to you when you sign up for a new aspects of the Service or if you take advantage of a new promotion or special offer which, if you use those aspects, promotions, or offers, become part of the Agreement. If any additional terms conflict with this Agreement, those additional terms will prevail. If you have any questions about this Agreement or the Services, please contact Videotc.</p>
                    <p>Videotc offers the Services only upon your unconditional acceptance of the terms and conditions without modification. You may be required to agree to additional terms to access additional features of the Services. In the event such additional terms conflict with the terms of this Agreement, such additional terms shall control.  From time to time, Videotc may change the terms of this Agreement and/or discontinue the Services at any time, without notice or liability to you. All such modifications shall become effective immediately. It is your responsibility to check for any changes each time you access the Services. Your continued use of the Services after the posting of any changes shall constitute your agreement with, and acceptance of, such changes.  In the event you do not agree to abide by the terms of this Agreement, you must not use the Services in any manner. MISUSE OF THE SERVICES MAY SUBJECT YOU TO CIVIL AND/OR CRIMINAL LIABILITY.</p>
                    <h3>No Storage</h3>
                    <p>You are soley in charge of downloading and/or backing up any of your content you wish to preserve. If you wish to preserve any of your content, you must back up such content on storage facilities under your control and unrelated to Videotc. You hereby acknowledge that Videotc, in its sole discretion, may remove and/or delete all or a portion your Submissions, as well as any additional information collected from, or about you, or produced for you, at any time, without notice or liability to you.</p>
                    <h3>Fees</h3>
                    <p>Regardless of the fees (if any) Videotc charges you to access or use the Website at any given time, Videotc reserves the right to change its fee structure at any time, without notice to you.  You hereby acknowledge that such fee changes may restrict your access to the Services and content.</p>
                    <h3>Arbitration Notice</h3>
                    <p>Except as specifically provided in this Agreement, you agree that any dispute or controversy arising out of, relating to or in connection with the interpretation, validity, construction, performance, breach or termination of this Agreement shall be submitted to binding, individual arbitration to be held in Burlington, Iowa in accordance with the rules of the American Arbitration Association (the "Rules") AND YOU HEREBY WAIVE YOUR RIGHT TO PARTICIPATE IN A CLASS ACTION LAWSUIT OR CLASS-WIDE ARBITRATION DIRECTLY OR INDIRECTLY RELATING TO THE PROVISION OF, OR FAILURE TO PROVIDE, THE SERVICES. The decision of the arbitrator shall be final, conclusive and binding on the parties to the arbitration. Judgment may be entered on the arbitrator's decision in any court of competent jurisdiction. The parties shall each bear their own attorney fees with respect to such Arbitration but shall share equally the other costs and expenses of arbitration. </p>
                    <p>PLEASE READ THIS SECTION CAREFULLY. IT AFFECTS YOUR LEGAL RIGHTS, INCLUDING YOUR RIGHT TO FILE A LAWSUIT IN COURT.</p>
                    <p>In the event a dispute arises between you and Videotc, you hereby agree to initially try to informatlly resolve the dispute by contacting Videotc directly.</p>
                    <h3>For U.S. Customers:</h3>
                    <p>Both you and Videotc agree that the following terms affect interstate commerce and are governed, interpreted, and enforceable, by and under the Federal Arbitration Act:</p>
                    <p>Other than the following three exceptions, you and Videotc agree that if any dispute with Videotc remains unresolved thirty (30) days after you contact Vidoetc, then you agree that you and Videotc will resolve the dispute through final and binding arbitration:</p>
                    <ol>
                        <li>You may bring an action in small claims court.</li>
                        <li>For a claim of infringement or other misuse of intellectual property rights both you and Videotc may bring a suit in any court in the state of Iowa only. In such an event, both you and Videotc waive any right to a jury trial.</li>
                        <li>You are free to bring any claim to the attention of a relevant federal, state, or local agency to seek relief against Videotc on your behalf.</li>
                    </ol>
                    <p>In the event you terminate a subscription with Videotc for breach after the thrity (30) day resolution period, during which the breach remains uncured, Videotc will refund any pre-paid fees to you on a pro-rata basis.</p>
                    <h3>Arbitration Rules</h3>
                    <p>Arbitration will be conducted by the Judicial Arbitration Mediation Service (“JAMS”) in accordance with the JAMS Streamlined Arbitration Procedure Rules for claims that do not exceed $250,000 and the JAMS Comprehensive Arbitration Rules and Procedures for claims exceeding $250,000 in effect at the time the arbitration is initiated, excluding any rules or procedures governing or permitting class actions. The arbitrator, and not any federal, state, or local court or agency, shall have exclusive authority to resolve all disputes arising out of or relating to the interpretation, applicability, enforceability, or formation of these Terms or the Privacy Statement, including but not limited to any claim that all or any part of these Terms or Privacy Statement is void or voidable, whether a claim is subject to arbitration, or the question of waiver by litigation conduct. The arbitrator shall be empowered to grant whatever relief would be available in a court under law or in equity. The arbitrator’s award shall be written and shall be binding on the parties and may be entered as a judgment in any court of competent jurisdiction. To start an arbitration, you must do the following: (a) write a Demand for Arbitration that includes a description of the claim and the amount of damages you seek to recover (you may find a copy of a Demand for Arbitration at www.jamsadr.com); (b) send three copies of the Demand for Arbitration, plus the appropriate filing fee, to JAMS, Two Embarcadero Center, Suite 1500, San Francisco, California 94111; and (c) send one copy of the Demand for Arbitration Videotc Legal Department, 320 North 3rd Street, Suite 100 Burlington, Iowa 52601. Arbitration may take place in the county where you reside at the time of filing. You and Videotc further agree to submit to the personal jurisdiction of any federal or state court in Des Moines County, Iowa in order to compel arbitration, to stay proceedings pending arbitration, or to confirm, modify, vacate, or enter judgment on the award entered by the arbitrator.</p>
                    <h3>Fees</h3>
                    <p>You will be required to pay $250 to initiate an arbitration against Videotc. If the arbitrator finds the arbitration to be non-frivolous, Videotc  will pay all other fees invoiced by JAMS, including filing fees and arbitrator and hearing expenses. You are responsible for your own attorneys’ fees unless the arbitration rules and/or applicable law provide otherwise.</p>
                    <h3>No Class Actions</h3>
                    <p>You and Videotc each agree that each party may only resolve disputes with the other on an individual basis and may not bring a claim as a plaintiff or a class member in a class, consolidated, or representative action. If any court or arbitrator determines that the class action waiver set forth in this paragraph is void or unenforceable for any reason or that an arbitration can proceed on a class basis, then the arbitration provisions set forth above shall be deemed null and void in their entirety and the parties shall be deemed to have not agreed to arbitrate disputes.</p>
                    <h3>Changes to This Section</h3>
                    <p>Videotc will provide thirty (30) days’ notice of any changes affecting the substance of this section by posting notice of modifications to the Terms on the Services, sending you a message, or otherwise notifying you when you are logged into your account. Amendments will become effective thirty (30) days after they are posted on the Services or sent to you.</p>
                    <p>Changes to this section will otherwise apply prospectively only to claims arising after the thirtieth (30th) day. If a court or arbitrator decides that this subsection on "Changes to This Section" is not enforceable or valid, then this subsection shall be severed from the section entitled “Dispute, Resolution, Arbitration and Class Action Waiver,” and the court or arbitrator shall apply the first Arbitration and Class Action Waiver section in existence after you began using the Services.</p>
                    <p>All of the foregoing arbitration provisions shall survive any termination of your account, this Agreement, or the Services.</p>
                    <p>Videos, Photos, Comments, Reviews, and Other Content. You are free to post or submit comments, photographs, videos, reviews, suggestions, ideas, questions, as well as other content, communication, and information (collectively “Submissions”) through or to the Services. Provided however, you are not authorized to post or submit any Submissions, that contain, in whole or in part, software viruses, commercial solicitation, requests to republish the Submission, political campaigning, mass mailings, or any form unsolicited commercial electronic messages. You are not authorized to post or submit any Submissions that are associated with a false or misleading e-mail address or that falsely imply an identity, association, or affiliation with another person or entity.  Although Videotc does not regularly review Submissions, Videotc reserves the right, but not the obligation, to edit or remove any Submission at its sole discretion.</p>
                    <p>By posting or submitting Submissions, you hereby grant Videotc an irrevocable, perpetual, worldwide, nonexclusive, royalty-free, and fully sublicensable right to use, distribute, copy, display, modify, translate, adapt, publish, perform, translate, and create derivative works from such Submissions in any format or media. By posting or submitting Submissions, you also grant Videotc and its sublicensees the right, but no the obligation, to use the name used to post or submit the Submissions (collectively the “License”). Videotc expressly disclaims all liability associated with any Submission posted by you or any other person or entity. </p>
                    <p>Videotc does not own your Submissions, but you herby grant Videotc the License to use all of your Submissions. You still own your Submissions and you remain free to share your Submissions with anyone else, wherever you want. Videotc does need the License to provide you with the Services. When you share, post, or upload content that is covered by intellectual property rights (like photos or videos) on or in connection with Videotc’s Service, you hereby grant Videotc the License in the form of a non-exclusive, royalty-free, transferable, sub-licensable, worldwide license to host, use, distribute, modify, run, copy, publicly perform or display, translate, and create derivative works of your Submissions (consistent with your privacy and application settings). This License will end when your Submissions is deleted from Videotc’s systems. You can delete your Submissions individually or all at once by deleting your account.</p>
                    <p>Permission to use your username, profile picture, and information about your relationships and actions with accounts, ads, and sponsored content.</p>
                    <p>By using the Services, you hereby give Videotc the right to show your username, profile picture, and information about your actions (such as likes) or relationships (such as follows) next to or in connection with accounts, ads, offers, and other sponsored content that you follow or engage with that are displayed on Videotc and its properties, without any compensation to you. For example, Videotc may show that you liked a sponsored post created by a brand that has paid Videotc to display its ads onVideotc. As with actions on other content and follows of other accounts, actions on sponsored content and follows of sponsored accounts can be seen only by people who have permission to see that content or follow. Videotc will also respect your ad settings.</p>
                    <p>You agree that Videotc can download and install updates to the Service on your device.</p>
                    <p>You are solely responsible for your Submissions;</p>
                    <p>You must have all the necessary legal rights to upload or post your Submissions;</p>
                    <p>Any Submissions you provide complies with Videotc’s rules;</p>
                    <p>You will provide Videotc upon Videotc’s request, with any documentation necessary to evidence your compliance with these Terms; and Any Submissions that you have shared publicly (e.g. by including such Submissions as part of your public profile in one of the Services or in a public posting on one of Videotc’s Services) may be used by other users as part of, or in conjunction with, the Services. Videotc will not be required to remove any Submissions that you have made public or has otherwise been shared from public profiles of other users.</p>
                    <h3>Content Removal</h3>
                    <p>Videotc may cease providing you with Services at any time, without notice to you, if Videotc believes, in its sole discretion, that the your use of the Services and/or any Submission violates these Terms of Use, Videotc’s policies, or if Videotc is permitted or required to do so by law. Videotc may refuse to provide or stop providing all or part of the Services immediately: 1) to protect Videotc’s community or services; 2) to avoid or mitigate any risk or legal exposure for Videotc; 3) if you violate these Terms of Use or Videotc’s policies; 4) if you infringe other people's intellectual property rights; or 5) where Videotc is permitted or required to do so by law. In the event Videotc determines that doing so is reasonably necessary to avoid or mitigate adverse legal or regulatory impacts on Videotc, Videotc may also terminate or change the Service, remove or block content or information shared on Videotc’s Service, or stop providing all or part of the Service. If you believe your account has been terminated in error, or you want to disable or permanently delete your account, contact Videotc immediately. When you request to delete content or your account, the deletion process will automatically begin no more than sixty (60) days after your request. It may take up to one hundred and twenty (120) days to delete content after the deletion process begins. After the content is deleted, it may take Videotc up to another ninety (90) days to remove the content from backups and disaster recovery systems.</p>
                    <p>In the following circumstances, content may not be deleted, despite a request that it be deleted:</p>
                    <ul>
                        <li>If the content has been used by others in accordance with this license and they have not deleted it (in which case this license will continue to apply until that content is deleted); or</li>
                        <li>If deletion within one hundred and twenty (120) is not possible due to technical limitations of Videotc’s systems, in which case, Videotc will complete the deletion as soon as technically feasible; or</li>
                        <li>If deletion would restrict Videotc’s ability to:</li>
                        <li>investigate or identify illegal activity or violations of Videotc’s terms and policies (for example, to identify or investigate misuse of Videotc’s products or systems);</li>
                        <li>protect the safety and security of Videotc’s products, systems, and users;</li>
                        <li>comply with a legal obligation, such as the preservation of evidence; or</li>
                        <li>comply with a request of a judicial or administrative authority, law enforcement, or a government agency;</li>
                        <li>in which case, the content will be retained for no longer than is necessary for the purposes for which it has been retained (the exact duration will vary on a case-by-case basis).</li>
                    </ul>
                    <p>If you delete or Videotc disables your account, these Terms shall terminate as an agreement between you and us, but this section and other sections pertaining to disputes will apply even after termination.</p>
                    <p>If Videotc terminates or determines the need to suspend all or part of the service, Videotc will provide you notice per the notification information you provide Videotc and give you notice of the date the service will be suspended and terminated. For that reason it is incumbent upon you to maintain a copy of all content you upload and provide to Videotc. </p>
                    <p>Automatic Subscription Renewals. Unless otherwise specifically stated in the terms of your offer, your subscription to Videotc shall automatically renew. Immediately upon the end of your free trial and/or as soon as you become a subscribing member, your subscription will automatically renew based on the subscription program you chose (e.g. weekly, monthly, quarterly, annually, etc.). Youre renewal will be charged the then-current rate for the subscription program you are on (plus applicable taxes, such as value added tax when the stated rate does not include VAT) at the beginning of each billing term of your subscription via the billing method you have provided to Videotc. To prevent an interruption in your subscription, it is important that you ensure that your billing information is always current and correct.</p>
                    <p>Prices and terms for subscriptions may change at any time. The price and terms in place when you made your initial purchase or when your subscription last renewed will stay in effect for the duration of that subscription period, but new prices and terms may apply to renewals or new subscriptions. The maximum subscription term will be one (1) year and will need renewed after the one (1) year anniversary of your subscription. Videotc will give you reasonable notice of any change in price or terms before they go into effect. If you do not want to renew your subscription under these new prices or terms, you may cancel your subscription as described below. Videotc anticipates modifications to rates of subscription based on usage which could result in a decrease or increase of the subscription, post free trial period.</p>
                    <p>Subscription Cancellations and Refunds. You may cancel your Videotc subscription by logging into your account or by contacting us.</p>
                    <p>Unless otherwise stated in the terms of your subscription, the following terms will apply:</p>
                    <h3>Free Trials</h3>
                    <p>Some of the Services allow you to register for a free trial so you can try the Services before starting a paid subscription. If you register for a free trial, you may cancel at any time prior to seven days before the end of the free trial period and incur no charge. If you do not cancel by that time, your paid subscription will start once your free trial period ends. One free trial per user. After a free trial bills through, no refunds will be issued. For users located in the European Union, your free trial is inclusive of your cooling off rights.</p>
                    <h3>Monthly Subscriptions</h3>
                    <p>Subscriptions billed on a monthly basis may be canceled at any time prior to two business days before your renewal date but are not eligible for a refund. If you cancel your monthly subscription, you will retain access to your Services for the remainder of that month. If you do not cancel your subscription prior to two days before your renewal date, we will renew your subscription for one more month.</p>
                    <h3>Videotc subscriptions</h3>
                    <p>Except as outlined below, if you cancel this type of subscription before the end of your subscription period, you are not eligible for a refund, but you will retain access to the relevant Services for the remainder of your subscription period, after which your subscription will be cancelled. If you do not cancel your subscription within your subscription period, we will renew your subscription for additional terms equivalent in length to your current subscription, until you cancel. After your subscription renews, you are not eligible for any refunds. Refunds are not based on account usage.
                    Subscriptions Longer than a Month, Billed Monthly. Where offered, some subscriptions longer than a month may be eligible for monthly billing. Even though you will be billed monthly, you are committing to the entire length of your subscription (e.g. 6 months or 12 months). Except as outlined below, if you cancel this type of subscription before the end of your subscription term, you are not eligible for a refund, but you will retain access to the relevant Services for the remainder of any paid months (after which your subscription will be cancelled), and you may be charged a cancellation fee. If you do not cancel your subscription within your subscription period, we will renew your subscription for additional terms equivalent in length to your current subscription, until you cancel. After your subscription renews, you are not eligible for any refunds.</p>
                    <h3>Taxes and Fees</h3>
                    <p>You will be responsible for all taxes and fees charged by other companies such as shipping, mobile carrier fees, data plan charges, overdraft fees, credit card fees, and foreign transaction fees.</p>
                    <h3>Updating your Payment Methods</h3>
                    <p>You can update your Payment Methods by going to the "Account" page. We may also update your Payment Methods using information provided by the payment service providers. Following any update, you authorize us to continue to charge the applicable Payment Method(s).</p>

                </div>
            </div>
        </div>
    </section>
</template>